name: taswekshope-gif/DAHAP
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ https://taswekshope-gif.github.io/DAHAP/#order }}
    steps:
      - uses: actions/checkout@v4
      - name: DAHAP
        run: # your build commands
      - name: taswekshope-gif
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: DAHAP
        uses: actions/deploy-pages@v4
