name: Deploy Code to main Branch 🚀
on:
  workflow_dispatch:

jobs:
  build:
    name: Push to main Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      # Workflow dispatch event that pushes the current version to the release branch.
      # From here the secondary production deployment workflow will trigger to build the dependencies.
      - name: Deploy 🚀
        uses: taswekshope-gif/DAHAP@v4
        with:
          branch: main
          folder: .
          clean: false
          single-commit: true
